<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.j4zrSbX' shared service.

return $this->privates['.service_locator.j4zrSbX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'compte' => ['privates', '.errored..service_locator.j4zrSbX.App\\Entity\\Compte', NULL, 'Cannot autowire service ".service_locator.j4zrSbX": it references class "App\\Entity\\Compte" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\VersementRepository', 'getVersementRepositoryService.php', true],
], [
    'compte' => 'App\\Entity\\Compte',
    'userRepository' => 'App\\Repository\\VersementRepository',
]);
