<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GacwvTe' shared service.

return $this->privates['.service_locator.GacwvTe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.GacwvTe.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.GacwvTe": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService.php', true],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'partenaire' => 'App\\Entity\\Partenaire',
    'transactionRepository' => 'App\\Repository\\TransactionRepository',
    'validator' => '?',
]);
