<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.RQ6fYdz' shared service.

return $this->privates['.service_locator.RQ6fYdz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.RQ6fYdz.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.RQ6fYdz": it references class "App\\Entity\\User" but no such service exists.'],
    'validator' => ['services', 'validator', 'getValidatorService', false],
], [
    'user' => 'App\\Entity\\User',
    'validator' => '?',
]);
