<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qAHeKl0' shared service.

return $this->privates['.service_locator.qAHeKl0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.qAHeKl0.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.qAHeKl0": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'partenaire' => 'App\\Entity\\Partenaire',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
