<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MFShk5N' shared service.

return $this->privates['.service_locator.MFShk5N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tarifRepository' => ['privates', 'App\\Repository\\TarifsRepository', 'getTarifsRepositoryService.php', true],
], [
    'tarifRepository' => 'App\\Repository\\TarifsRepository',
]);
